apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sampleapp
  template:
    metadata:
      labels:
        run: sampleapp
    spec:
      containers:
      - name: sampleapp-site
        image: sixartifact.jfrog.io/default-docker-local/sampleapp:v1.0
        ports:
          - containerPort: 8080
            protocol: TCP
      # The Docker image for this application is stored in Azure Container Registry, which requires authentication.
      # To allow Azure Kubernetes Service to pull images from this registry, we need to create a kubernetes secret
      # using the following commands:
      #
      # docker login pythonapppoc.azurecr.io
      # kubectl create secret docker-registry regcred --docker-server=parneraws-docker.jfrog.io --docker-username=admin --docker-password=[your_password] --docker-email=[your_email]
      imagePullSecrets:
      - name: sampleapp5
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-entrypoint
spec:
  selector:
    run: sampleapp
  type: LoadBalancer
  ports:
    - port: 8080
